[2025-10-05T18:35:08.585+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: news_wordcount_pipeline.save_report_task manual__2025-10-05T18:35:01.545884+00:00 [queued]>
[2025-10-05T18:35:08.602+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: news_wordcount_pipeline.save_report_task manual__2025-10-05T18:35:01.545884+00:00 [queued]>
[2025-10-05T18:35:08.603+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-05T18:35:08.604+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-10-05T18:35:08.604+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-05T18:35:08.627+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): save_report_task> on 2025-10-05 18:35:01.545884+00:00
[2025-10-05T18:35:08.639+0000] {standard_task_runner.py:55} INFO - Started process 151 to run task
[2025-10-05T18:35:08.645+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'news_wordcount_pipeline', 'save_report_task', 'manual__2025-10-05T18:35:01.545884+00:00', '--job-id', '24', '--raw', '--subdir', 'DAGS_FOLDER/news_wordcount_dag.py', '--cfg-path', '/tmp/tmp9vaqfkyv']
[2025-10-05T18:35:08.652+0000] {standard_task_runner.py:83} INFO - Job 24: Subtask save_report_task
[2025-10-05T18:35:08.768+0000] {task_command.py:388} INFO - Running <TaskInstance: news_wordcount_pipeline.save_report_task manual__2025-10-05T18:35:01.545884+00:00 [running]> on host ca12f4cec8a5
[2025-10-05T18:35:08.898+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=news_wordcount_pipeline
AIRFLOW_CTX_TASK_ID=save_report_task
AIRFLOW_CTX_EXECUTION_DATE=2025-10-05T18:35:01.545884+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-05T18:35:01.545884+00:00
[2025-10-05T18:35:08.903+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/src/news_utils.py", line 43, in save_report
    df = pd.DataFrame(word_counts.most_common(10), columns=["word", "count"])
AttributeError: 'dict' object has no attribute 'most_common'
[2025-10-05T18:35:08.929+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=news_wordcount_pipeline, task_id=save_report_task, execution_date=20251005T183501, start_date=20251005T183508, end_date=20251005T183508
[2025-10-05T18:35:08.956+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 24 for task save_report_task ('dict' object has no attribute 'most_common'; 151)
[2025-10-05T18:35:09.018+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-05T18:35:09.074+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
