[2025-10-05T18:40:25.163+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: news_wordcount_pipeline.save_report_task manual__2025-10-05T18:40:18.632442+00:00 [queued]>
[2025-10-05T18:40:25.186+0000] {taskinstance.py:1083} INFO - Dependencies all met for <TaskInstance: news_wordcount_pipeline.save_report_task manual__2025-10-05T18:40:18.632442+00:00 [queued]>
[2025-10-05T18:40:25.187+0000] {taskinstance.py:1279} INFO - 
--------------------------------------------------------------------------------
[2025-10-05T18:40:25.188+0000] {taskinstance.py:1280} INFO - Starting attempt 1 of 1
[2025-10-05T18:40:25.189+0000] {taskinstance.py:1281} INFO - 
--------------------------------------------------------------------------------
[2025-10-05T18:40:25.212+0000] {taskinstance.py:1300} INFO - Executing <Task(PythonOperator): save_report_task> on 2025-10-05 18:40:18.632442+00:00
[2025-10-05T18:40:25.226+0000] {standard_task_runner.py:55} INFO - Started process 136 to run task
[2025-10-05T18:40:25.234+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'news_wordcount_pipeline', 'save_report_task', 'manual__2025-10-05T18:40:18.632442+00:00', '--job-id', '30', '--raw', '--subdir', 'DAGS_FOLDER/news_wordcount_dag.py', '--cfg-path', '/tmp/tmpr0t9sqzy']
[2025-10-05T18:40:25.239+0000] {standard_task_runner.py:83} INFO - Job 30: Subtask save_report_task
[2025-10-05T18:40:25.362+0000] {task_command.py:388} INFO - Running <TaskInstance: news_wordcount_pipeline.save_report_task manual__2025-10-05T18:40:18.632442+00:00 [running]> on host ca12f4cec8a5
[2025-10-05T18:40:25.477+0000] {taskinstance.py:1509} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=your_name
AIRFLOW_CTX_DAG_ID=news_wordcount_pipeline
AIRFLOW_CTX_TASK_ID=save_report_task
AIRFLOW_CTX_EXECUTION_DATE=2025-10-05T18:40:18.632442+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2025-10-05T18:40:18.632442+00:00
[2025-10-05T18:40:25.511+0000] {taskinstance.py:1768} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 175, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 192, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/news_wordcount_dag.py", line 44, in save_report_task_callable
    save_report(word_counts)
  File "/opt/airflow/dags/src/news_utils.py", line 43, in save_report
    df = pd.DataFrame(word_counts.most_common(10), columns=["word", "count"])
AttributeError: 'dict' object has no attribute 'most_common'
[2025-10-05T18:40:25.539+0000] {taskinstance.py:1323} INFO - Marking task as FAILED. dag_id=news_wordcount_pipeline, task_id=save_report_task, execution_date=20251005T184018, start_date=20251005T184025, end_date=20251005T184025
[2025-10-05T18:40:25.564+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 30 for task save_report_task ('dict' object has no attribute 'most_common'; 136)
[2025-10-05T18:40:25.606+0000] {local_task_job.py:208} INFO - Task exited with return code 1
[2025-10-05T18:40:25.630+0000] {taskinstance.py:2578} INFO - 0 downstream tasks scheduled from follow-on schedule check
